# For more samples to get started with GitHub Action workflows to deploy to Azure: https://github.com/Azure/actions-workflow-samples

on:
  push:
    branches: ['devops']
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: FOCUS_POC
  #AZURE_WEBAPP_PACKAGE_PATH: 'drop' 
  NODE_VERSION: '18.x' 

permissions:
  contents: read

jobs:
job1 :
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: npm install, build, and test
        run: |
          npm ci
          npm run lint --if-present
          npm run test --if-present
          npm run build --if-present
          
      - name: Zip artifact for deployment
        run: zip nodeapp.zip ./* -r
        
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: nodeapp.zip
          
      #- name: Download artifact
      #  uses: actions/download-artifact@v3
      #  with: 
      #    name: node-app
      
      - name: view artifact path
        run: ls -R
  job2:      
 - name: Veracode Static Analysis
#      on:
#   workflow_dispatch:
#   pull_request:
#     branches:
#       - production
#       - beta
#       - staging
#       - develop
#       - Release**

# jobs:
#   check-code:
#     runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@v2
#       - name: Zip Folder
#         run: zip -r release.zip ./src
      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.4
        with:
          appname: 'GX-core-services'
          createprofile: false
          filepath: 'nodeapp.zip'
          vid: '${{ secrets.VERACODE_ID }}'
          vkey: '${{ secrets.VERACODE_KEY }}'
#   deploy:
#     permissions:
#       contents: none
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Development'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

#     steps:
#     - name: Download artifact from build job
#       uses: actions/download-artifact@v3
#       with:
#         name: node-app

#     - name: 'Deploy to Azure WebApp'
#       id: deploy-to-webapp
#       uses: azure/webapps-deploy@v2
#       with:
#         app-name: ${{ env.AZURE_WEBAPP_NAME }}
#         publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
#         package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

